include(${CMAKE_SOURCE_DIR}/cmake/macro.cmake)

set(CONTROLLER_DIR ${CMAKE_SOURCE_DIR}/src/controller)


file(GLOB CONTROLLER_HEADER "${CONTROLLER_DIR}/*.h")
file(GLOB CONTROLLER_SOURCE "${CONTROLLER_DIR}/*.cpp")


set(CONTROLLER_RESOURCE ${CONTROLLER_HEADER} ${CONTROLLER_SOURCE})